version: '3.8' #為了跑gpu才加
services:
  # web:
  #   build: .
  #   ports:
  #      - "5000:5050"

  scraper:
    image: mcr.microsoft.com/playwright/python:v1.40.0-jammy
    volumes:
    - .:/app
    working_dir: /app
    command: tail -f /dev/null

  ai_trainer:
    image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
    shm_size: '8gb'
    volumes: #改外面程式裡面才能直接用
    - .:/app
    working_dir: /app #儲存位置
    command: >
      /bin/bash -c "
      pip install psycopg2-binary python-dotenv pandas pgvector && 
      tail -f /dev/null
      "       
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  db:
    image: pgvector/pgvector:pg16  # 直接使用編譯好 vector 的官方
    container_name: manhwa_vector_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}   # 設定超級管理員密碼
      POSTGRES_DB: manhwa          # 容器啟動時，會自動幫你建立 manhwa 資料庫
    ports:
      - "${DB_PORT_MAPPING}"                # 映射到外部，讓你的 pgAdmin 還是可以連進來
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: